### ISSUE TITLE
runtime error on RHEL 5

### ISSUE THREAD

**Issue by jmrodri** [dgoodwin/tito#1]
sudo yum install git python-setuptools python-hashlib
git clone .../tito
cd tito
sudo python setup.py install

cd sm-photo-tool
[jmrodri@corvette sm-photo-tool]$ tito build --tgz
Checking for tag [sm-photo-tool-1.16-2] in git repo [git://github.com/jmrodri/sm-photo-tool.git]
Traceback (most recent call last):
  File "/usr/bin/tito", line 5, in ?
    pkg_resources.run_script('tito==1.0', 'tito')
  File "/usr/lib/python2.4/site-packages/pkg_resources.py", line 448, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.4/site-packages/pkg_resources.py", line 1173, in run_script
    exec script_code in namespace, namespace
  File "/usr/bin/tito", line 23, in ?

  File "build/bdist.linux-i686/egg/tito/cli.py", line 109, in main
  File "build/bdist.linux-i686/egg/tito/cli.py", line 372, in main
  File "build/bdist.linux-i686/egg/tito/cli.py", line 387, in _create_builder
  File "build/bdist.linux-i686/egg/tito/cli.py", line 54, in get_class_by_name
TypeError: __import__() takes no keyword arguments

Works fine on my F11 install. I'll try to investigate.

**Comment by jmrodri** [comment]
@jumanjiman yeah we can totally close this issue. Who the heck still uses RHEL 5? :)
