### ISSUE TITLE
tito.spec build failure: __python2 is unset on EL6

### ISSUE THREAD

**Issue by domcleal** [dgoodwin/tito#167]
A build of the master branch is currently failing on EL6, as `__python2` is undefined.  Perhaps it should fallback to `__python`?

https://copr-be.cloud.fedoraproject.org/results/domcleal/tito-nightly/epel-6-i386/tito-0.5.6-1.git.4.4091af9.el6/build.log (http://copr-fe.cloud.fedoraproject.org/coprs/domcleal/tito-nightly/build/87103/)

<pre>
+ '%{__python2}' setup.py build
/var/tmp/rpm-tmp.nMwCVc: line 32: fg: no job control
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.nMwCVc (%build)
    Bad exit status from /var/tmp/rpm-tmp.nMwCVc (%build)
Child return code was: 1
EXCEPTION: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target i686 --nodeps  /builddir/build/SPECS/tito.spec 
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/mockbuild/trace_decorator.py", line 84, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.6/site-packages/mockbuild/util.py", line 504, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target i686 --nodeps  /builddir/build/SPECS/tito.spec 
LEAVE do --> EXCEPTION RAISED
</pre>

**Comment by domcleal** [comment]
Incidentally, the %prep section does this: `sed -i 1"s|#!/usr/bin/python|#!/usr/bin/python3|" bin/tito` irrespective of the platform.  Perhaps wrap that in a `use_python3` conditional, and use `pythonbin` too?
