### ISSUE TITLE
KojiReleaser building to two SCL-enabled tags does not clean up temporary builder

### ISSUE THREAD

**Issue by domcleal** [dgoodwin/tito#188]
When KojiBuilder is configured to build to multiple tags and they are all using SCLs (as per tito.props), tito builds SRPMs using a temporary in-memory copy of the builder (which it enables the 'scl' option on) but it doesn't ever call the cleanup routine.  This causes a problem when using a GitAnnexBuilder, since the clean/dirty state is important when locking and unlocking files.

Slightly simplified example:

releasers.conf:

<pre>
[koji-foreman]
releaser = tito.release.KojiReleaser
autobuild_tags = foreman-nightly-rhel6 foreman-nightly-rhel7
</pre>

tito.props:

<pre>
[foreman-nightly-rhel6]
disttag = .el6
scl = ruby193

[foreman-nightly-rhel7]
disttag = .el7
scl = ruby193
</pre>

When releasing, the second tag fails:

<pre>
$ tito release koji-foreman --test --scratch --debug
Added lib dir to PYTHONPATH: /home/dcleal/code/foreman/foreman-packaging/rel-eng/custom/
Will release to the following targets: koji-foreman
Releasing to target: koji-foreman
Importing tito.release.KojiReleaser
Using releaser class: <class 'tito.release.main.KojiReleaser'>
Parsed custom builder args: {}
---- Builder class is None
Importing tito.builder.GitAnnexBuilder
Using builder class: <class 'tito.builder.main.GitAnnexBuilder'>
Building in temp dir: /tmp/tito/rpmbuild-rubygem-pgmEIyLV
Getting latest package info from: /home/dcleal/code/foreman/foreman-packaging/rel-eng/packages/rubygem-pg
tag - rubygem-pg-0.12.2-8
output - fatal: No tags can describe '05be91cb9a05a4de496dfd55aecff60cc42e14fd'.
Try --always, or create some tags.
git describe of tag rubygem-pg-0.12.2-8 failed (32768)
Got package metadata: ['0.12.2-8', 'rubygem-pg/']
Working in: /tmp/tito/release-rubygem-pgRFXY7b
Building release in Koji...
Koji tags: ['foreman-nightly-rhel6', 'foreman-nightly-rhel7']
Creating rubygem-pg-git-0.05be91c.tar.gz from git tag: 25f6083371d7232cd3d16330ff8d27794e0b9120...
git-archive fails if relative dir is not in git tree
Command: git archive --format=tar --prefix=rubygem-pg-git-0.05be91c/ 25f6083371d7232cd3d16330ff8d27794e0b9120:rubygem-pg/ --output=/tmp/tito/rpmbuild-rubygem-pgmEIyLV/SOURCES/rubygem-pg-git-0.05be91c.tar.initial > /dev/null

Status code: 0

Command output: 

Copying git source to: /tmp/tito/rpmbuild-rubygem-pgmEIyLV/SOURCES/rubygem-pg-git-0.05be91c

Command: ls -lR /tmp/tito/rpmbuild-rubygem-pgmEIyLV/SOURCES/rubygem-pg-git-0.05be91c/

Status code: 0

Command output: /tmp/tito/rpmbuild-rubygem-pgmEIyLV/SOURCES/rubygem-pg-git-0.05be91c/:
total 12
lrwxrwxrwx. 1 dcleal dcleal  203 Jul 24 08:34 pg-0.12.2.gem -> ../.git/annex/objects/5w/k1/SHA256E-s108032--6dd15c3fa7219a4126243d5a32fe6182b9f8d4b2497f61f1b949df2fabf35ee8.2.gem/SHA256E-s108032--6dd15c3fa7219a4126243d5a32fe6182b9f8d4b2497f61f1b949df2fabf35ee8.2.gem
-rw-rw-r--. 1 dcleal dcleal 4957 Jul 24 08:34 rubygem-pg.spec

Looking for .spec in /tmp/tito/rpmbuild-rubygem-pgmEIyLV/SOURCES/rubygem-pg-git-0.05be91c
Using file: rubygem-pg.spec
  Annex files: ['pg-0.12.2.gem']
Copying unlocked file pg-0.12.2.gem
Scanning for sources.
  Sources: ['/tmp/tito/rpmbuild-rubygem-pgmEIyLV/SOURCES/rubygem-pg-git-0.05be91c/pg-0.12.2.gem']
setup_test_specfile:commit_count = 0
Creating srpm from spec file: /tmp/tito/rpmbuild-rubygem-pgmEIyLV/SOURCES/rubygem-pg-git-0.05be91c/rubygem-pg.spec
using dist: .el6
Wrote: /tmp/tito/ruby193-rubygem-pg-0.12.2-8.git.0.25f6083.el6.src.rpm

Found wrote line: /tmp/tito/ruby193-rubygem-pg-0.12.2-8.git.0.25f6083.el6.src.rpm

Submitting build with: koji -c ~/.koji/katello-config build --nowait --scratch foreman-nightly-rhel6 /tmp/tito/ruby193-rubygem-pg-0.12.2-8.git.0.25f6083.el6.src.rpm
Uploading srpm: /tmp/tito/ruby193-rubygem-pg-0.12.2-8.git.0.25f6083.el6.src.rpm
[====================================] 100% 00:00:00 111.04 KiB 143.46 KiB/sec
Created task: 305552
Task info: http://koji.katello.org/koji/taskinfo?taskID=305552
Creating rubygem-pg-git-0.05be91c.tar.gz from git tag: 25f6083371d7232cd3d16330ff8d27794e0b9120...
git-archive fails if relative dir is not in git tree
Command: git archive --format=tar --prefix=rubygem-pg-git-0.05be91c/ 25f6083371d7232cd3d16330ff8d27794e0b9120:rubygem-pg/ --output=/tmp/tito/rpmbuild-rubygem-pgmEIyLV/SOURCES/rubygem-pg-git-0.05be91c.tar.initial > /dev/null

Status code: 0

Command output: 

Copying git source to: /tmp/tito/rpmbuild-rubygem-pgmEIyLV/SOURCES/rubygem-pg-git-0.05be91c

Command: ls -lR /tmp/tito/rpmbuild-rubygem-pgmEIyLV/SOURCES/rubygem-pg-git-0.05be91c/

Status code: 0

Command output: /tmp/tito/rpmbuild-rubygem-pgmEIyLV/SOURCES/rubygem-pg-git-0.05be91c/:
total 12
lrwxrwxrwx. 1 dcleal dcleal  203 Jul 24 08:34 pg-0.12.2.gem -> ../.git/annex/objects/5w/k1/SHA256E-s108032--6dd15c3fa7219a4126243d5a32fe6182b9f8d4b2497f61f1b949df2fabf35ee8.2.gem/SHA256E-s108032--6dd15c3fa7219a4126243d5a32fe6182b9f8d4b2497f61f1b949df2fabf35ee8.2.gem
-rw-rw-r--. 1 dcleal dcleal 4957 Jul 24 08:34 rubygem-pg.spec

Looking for .spec in /tmp/tito/rpmbuild-rubygem-pgmEIyLV/SOURCES/rubygem-pg-git-0.05be91c
Using file: rubygem-pg.spec
ERROR: Error running command: git-annex lock

Status code: 256

Command output: lock pg-0.12.2.gem git-annex: Locking this file would discard any changes you have made to it. Use 'git annex add' to stage your changes. (Or, use --force to override)

Cleaning up [/tmp/tito/release-rubygem-pgRFXY7b]
Cleaning up /tmp/tito/rpmbuild-rubygem-pgmEIyLV
Traceback (most recent call last):
  File "/usr/bin/tito", line 23, in <module>
    CLI().main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 220, in main
    return module.main(argv)
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 613, in main
    scratch=self.options.scratch)
  File "/usr/lib/python2.7/site-packages/tito/release/main.py", line 465, in release
    self._koji_release()
  File "/usr/lib/python2.7/site-packages/tito/release/main.py", line 530, in _koji_release
    builder.srpm(dist=disttag)
  File "/usr/lib/python2.7/site-packages/tito/builder/main.py", line 194, in srpm
    self.tgz()
  File "/usr/lib/python2.7/site-packages/tito/builder/main.py", line 555, in tgz
    self._setup_sources()
  File "/usr/lib/python2.7/site-packages/tito/builder/main.py", line 1186, in _setup_sources
    run_command("git-annex lock")
  File "/usr/lib/python2.7/site-packages/tito/common.py", line 398, in run_command
    raise RunCommandException(command, status, output)
tito.exception.RunCommandException: Error running command: git-annex lock
</pre>

What appears to be happening is that tito creates a temporary builder here that has the SCL option set:

https://github.com/dgoodwin/tito/blob/tito-0.6.1-1/src/tito/release/main.py#L522-L530

The sources get set up, the builder creates a tarball, then an SRPM and then is discarded.  The new SCL-enabled builder doesn't get cleaned up at all, so the working copy is left dirty (important for GitAnnexBuilder).

This all works fine if the first tag in the releaser's list is a non-SCL tag followed by SCL tags, since the builder that's copied for the SCL tags has already run once and created a tarball (which it caches I think, see ran_tgz).

**Comment by domcleal** [comment]
Fixed via #189.
