### ISSUE TITLE
Doesn't obey settings in releasers.conf

### ISSUE THREAD

**Issue by user501254** [dgoodwin/tito#205]
On omitting 'upload_command' and 'remote_location' variables, execution fails.
Error log:

    [ashesh@MISTRI paper-icon-theme] $ tito release paper-icon-theme 
    Will release to the following targets: paper-icon-theme
    Releasing to target: paper-icon-theme
    WARNING: unable to lookup latest package tag, building untagged test project
    WARNING: .tito/packages/paper-icon-theme doesn't exist in git, using current directory
    Working in: /tmp/tito/release-paper-icon-themerawbp6cn
    Traceback (most recent call last):
      File "/usr/bin/tito", line 23, in <module>
        CLI().main(sys.argv[1:])
      File "/usr/lib/python3.4/site-packages/tito/cli.py", line 220, in main
        return module.main(argv)
      File "/usr/lib/python3.4/site-packages/tito/cli.py", line 607, in main
        **kwargs)
      File "/usr/lib/python3.4/site-packages/tito/release/copr.py", line 33, in __init__
        auto_accept, **kwargs)
      File "/usr/lib/python3.4/site-packages/tito/release/main.py", line 441, in __init__
        **kwargs)
      File "/usr/lib/python3.4/site-packages/tito/release/main.py", line 100, in __init__
        self._check_releaser_config()
      File "/usr/lib/python3.4/site-packages/tito/release/main.py", line 125, in _check_releaser_config
        (self.target, opt))
    tito.exception.TitoException: Release target 'paper-icon-theme' missing required option 'upload_command'

**Comment by dgoodwin** [comment]
What version of tito are you using? Upload_command is still required in the latest release, you can omit it only if you are running the latest tito from git master. Next release this field should be able to be omitted.

**Comment by user501254** [comment]
I am using version 0.6.0 from the fedora repo.
Thank you for letting me know. I was following the wiki over here.
