### ISSUE TITLE
rpmbuild failure in CentOS tests

### ISSUE THREAD

**Issue by stevekuznetsov** [dgoodwin/tito#246]
```
=====================
titotest-centos-6
^[[1;3DUsing Python 2.6
Using nose 0.1
Running tito tests against: /home/sandbox/src
nose.selector: INFO: /home/sandbox/runtests.py is executable; skipped
test_lock_force_supported (functional.build_gitannex_tests.GitAnnexBuilderTests) ... ok
test_simple_build (functional.build_gitannex_tests.GitAnnexBuilderTests) ... ok
ERROR: Error running command: rpmbuild --define "_source_filedigest_algorithm md5"  --define "_binary_filedigest_algorithm md5"  --eval '%undefine scl' --define "_topdir /tmp/tmpgmXo1w-titotestoutput/rpmbuild-titouLUoS1" --define "_sourcedir /tmp/tmpgmXo1w-titotestoutput/rpmbuild-titouLUoS1/SOURCES" --define "_builddir /tmp/tmpgmXo1w-titotestoutput/rpmbuild-titouLUoS1/BUILD" --define "_srcrpmdir /tmp/tmpgmXo1w-titotestoutput" --define "_rpmdir /tmp/tmpgmXo1w-titotestoutput"   --noclean -ba /tmp/tmpgmXo1w-titotestoutput/rpmbuild-titouLUoS1/SOURCES/tito-git-20.98e27fc/tito.spec
ERROR
```

Is this an environment failure or something in the tests? Testing `master`.

**Comment by stevekuznetsov** [comment]
<details>
<summary> Here's a full test output: </summary>

```
=====================
titotest-centos-6
^[[1;3DUsing Python 2.6
Using nose 0.1
Running tito tests against: /home/sandbox/src
nose.selector: INFO: /home/sandbox/runtests.py is executable; skipped
test_lock_force_supported (functional.build_gitannex_tests.GitAnnexBuilderTests) ... ok
test_simple_build (functional.build_gitannex_tests.GitAnnexBuilderTests) ... ok
ERROR: Error running command: rpmbuild --define "_source_filedigest_algorithm md5"  --define "_binary_filedigest_algorithm md5"  --eval '%undefine scl' --define "_topdir /tmp/tmpgmXo1w-titotestoutput/rpmbuild-titouLUoS1" --define "_sourcedir /tmp/tmpgmXo1w-titotestoutput/rpmbuild-titouLUoS1/SOURCES" --define "_builddir /tmp/tmpgmXo1w-titotestoutput/rpmbuild-titouLUoS1/BUILD" --define "_srcrpmdir /tmp/tmpgmXo1w-titotestoutput" --define "_rpmdir /tmp/tmpgmXo1w-titotestoutput"   --noclean -ba /tmp/tmpgmXo1w-titotestoutput/rpmbuild-titouLUoS1/SOURCES/tito-git-20.98e27fc/tito.spec
ERROR
test_rpmbuild_options_from_kwargs (functional.builder_tests.BuilderTests) ... ok
test_rpmbuild_options_from_options (functional.builder_tests.BuilderTests) ... ok
test_rpmbuild_options_missing (functional.builder_tests.BuilderTests) ... ok
test_scl_from_kwargs (functional.builder_tests.BuilderTests) ... ok
test_scl_from_options (functional.builder_tests.BuilderTests) ... ok
test_untagged_test_build (functional.builder_tests.BuilderTests) ... ok
test_untagged_test_version (functional.builder_tests.BuilderTests) ... ok
Check that the version string in Cargo.toml file is the same as in spec file ... ok
Check presence of the Cargo.toml file in the last commit (tag) ... ok
test_simple_build_no_tag (functional.fetch_tests.FetchBuilderTests) ... ERROR: Error running command: rpmbuild --define "_source_filedigest_algorithm md5"  --define "_binary_filedigest_algorithm md5"  --eval '%undefine scl' --define "_topdir /tmp/tmpgBdSm_-titotestoutput/rpmbuild-extsrcdMmtUF" --define "_sourcedir /tmp/tmpgBdSm_-titotestoutput/rpmbuild-extsrcdMmtUF/SOURCES" --define "_builddir /tmp/tmpgBdSm_-titotestoutput/rpmbuild-extsrcdMmtUF/BUILD" --define "_srcrpmdir /tmp/tmpgBdSm_-titotestoutput" --define "_rpmdir /tmp/tmpgBdSm_-titotestoutput"   --noclean -ba /tmp/tmpgBdSm_-titotestoutput/rpmbuild-extsrcdMmtUF/SOURCES/extsrc.spec
ERROR
test_tag_rejected (functional.fetch_tests.FetchBuilderTests) ... ok
test_with_releaser (functional.fetch_tests.FetchBuilderTests) ... ok
test_build_rpm (functional.multiproject_tests.MultiProjectTests) ... ok
test_build_tgz (functional.multiproject_tests.MultiProjectTests) ... ok
test_initial_tag_keep_version (functional.multiproject_tests.MultiProjectTests) ... ok
test_release_tagger (functional.multiproject_tests.MultiProjectTests) ... ok
Make sure the template is applied and results in the correct file ... ok
test_multiple_project_names (functional.release_copr_tests.CoprReleaserTests) ... ok
test_no_remote_defined (functional.release_copr_tests.CoprReleaserTests) ... ok
test_with_releaser (functional.release_copr_tests.CoprReleaserTests) ... ok
test_with_remote_defined_in_user_conf (functional.release_copr_tests.CoprReleaserTests) ... ok
test_with_releaser (functional.release_yum_tests.YumReleaserTests) ... ok
test_build_latest_rpm (functional.singleproject_tests.SingleProjectTests) ... ok
test_build_latest_srpm (functional.singleproject_tests.SingleProjectTests) ... ok
test_build_rpm_tag (functional.singleproject_tests.SingleProjectTests) ... ok
test_build_srpm_tag (functional.singleproject_tests.SingleProjectTests) ... ok
test_build_tgz_tag (functional.singleproject_tests.SingleProjectTests) ... ok
test_init_worked (functional.singleproject_tests.SingleProjectTests) ... ok
test_initial_tag (functional.singleproject_tests.SingleProjectTests) ... ok
test_latest_tgz (functional.singleproject_tests.SingleProjectTests) ... ok
test_release (functional.singleproject_tests.SingleProjectTests) ... ok
test_release_override_builder (functional.singleproject_tests.SingleProjectTests) ... ok
test_tag (functional.singleproject_tests.SingleProjectTests) ... ok
test_tag_with_changelog (functional.singleproject_tests.SingleProjectTests) ... ok
test_tag_with_changelog_format (functional.singleproject_tests.SingleProjectTests) ... ok
test_tag_with_changelog_multiple (functional.singleproject_tests.SingleProjectTests) ... ok
test_tag_with_custom_message (functional.singleproject_tests.SingleProjectTests) ... ok
test_tag_with_custom_message_bad_placeholder (functional.singleproject_tests.SingleProjectTests) ... ERROR
test_tag_with_custom_message_containing_quotes (functional.singleproject_tests.SingleProjectTests) ... ok
test_tag_with_version (functional.singleproject_tests.SingleProjectTests) ... ok
test_undo_tag (functional.singleproject_tests.SingleProjectTests) ... ok
test_complicated_case (unit.common_tests.CargoTransformTest) ... ok
test_simple_case (unit.common_tests.CargoTransformTest) ... ok
test_renders_cheetah (unit.common_tests.CheetahRenderTest) ... ok
test_renders_cheetah_missing_result (unit.common_tests.CheetahRenderTest) ... ok
test_colors (unit.common_tests.CommonTests) ... ok
test_compare_version (unit.common_tests.CommonTests) ... ok
test_extract_sha1 (unit.common_tests.CommonTests) ... ok
test_find_file_with_extension (unit.common_tests.CommonTests) ... ok
test_find_file_with_extension_duplicates (unit.common_tests.CommonTests) ... ok
test_find_file_with_extension_no_match (unit.common_tests.CommonTests) ... ok
test_find_spec_like_file_no_match (unit.common_tests.CommonTests) ... ok
test_find_spec_like_file_spec (unit.common_tests.CommonTests) ... ok
test_find_spec_like_file_tmpl (unit.common_tests.CommonTests) ... ok
Test old spacewalk.releng namespace is converted to tito. ... ok
test_replace_version_crazy_new_version (unit.common_tests.CommonTests) ... ok
test_replace_version_crazy_old_version (unit.common_tests.CommonTests) ... ok
test_replace_version_double_quote (unit.common_tests.CommonTests) ... ok
test_replace_version_leading_whitespace (unit.common_tests.CommonTests) ... ok
test_replace_version_no_match (unit.common_tests.CommonTests) ... ok
test_replace_version_no_whitespace (unit.common_tests.CommonTests) ... ok
test_replace_version_some_whitespace (unit.common_tests.CommonTests) ... ok
test_replace_version_trailing_chars (unit.common_tests.CommonTests) ... ok
test_replace_version_uppercase (unit.common_tests.CommonTests) ... ok
test_rpmbuild_claims_to_be_successful (unit.common_tests.CommonTests) ... ok
test_rpmbuild_which_ended_with_error_is_described_with_the_analyzed_line (unit.common_tests.CommonTests) ... ok
test_run_command_print (unit.common_tests.CommonTests) ... ok
test_search_for (unit.common_tests.CommonTests) ... ok
test_search_for_gets_first_match (unit.common_tests.CommonTests) ... ok
test_search_for_no_match (unit.common_tests.CommonTests) ... ok
test_turn_off_colors (unit.common_tests.CommonTests) ... ok
test_bug_doesnt_exist (unit.common_tests.ExtractBugzillasTest) ... ok
test_diff_format (unit.common_tests.ExtractBugzillasTest) ... ok
test_multi_line (unit.common_tests.ExtractBugzillasTest) ... ok
test_required_flags_found (unit.common_tests.ExtractBugzillasTest) ... ok
test_required_flags_missing (unit.common_tests.ExtractBugzillasTest) ... ok
test_required_flags_missing_with_placeholder (unit.common_tests.ExtractBugzillasTest) ... ok
test_same_id_multiple_times (unit.common_tests.ExtractBugzillasTest) ... ok
test_single_line (unit.common_tests.ExtractBugzillasTest) ... ok
test_single_line_no_bz (unit.common_tests.ExtractBugzillasTest) ... ok
test_single_required_flag_found (unit.common_tests.ExtractBugzillasTest) ... ok
test_single_with_dash (unit.common_tests.ExtractBugzillasTest) ... ok
test_single_with_no_spaces (unit.common_tests.ExtractBugzillasTest) ... ok
test_autosetup (unit.common_tests.MungeSetupMacroTests) ... ERROR
test_setup (unit.common_tests.MungeSetupMacroTests) ... ok
test_complex_setup_transform (unit.common_tests.SpecTransformTest) ... ok
test_simple_transform (unit.common_tests.SpecTransformTest) ... ok
test_transform_no_whitespace_modifications (unit.common_tests.SpecTransformTest) ... ok
test_transform_release_only (unit.common_tests.SpecTransformTest) ... ok
test_empty_string (unit.common_tests.VersionMathTest) ... ok
test_increase_release (unit.common_tests.VersionMathTest) ... ok
test_increase_release_with_rpm_cruft (unit.common_tests.VersionMathTest) ... ok
test_increase_release_with_zstream (unit.common_tests.VersionMathTest) ... ok
test_increase_version_major (unit.common_tests.VersionMathTest) ... ok
test_increase_version_minor (unit.common_tests.VersionMathTest) ... ok
test_increase_versionless (unit.common_tests.VersionMathTest) ... ok
test_increase_zstream (unit.common_tests.VersionMathTest) ... ok
test_increase_zstream_already_appended (unit.common_tests.VersionMathTest) ... ok
test_reset_release (unit.common_tests.VersionMathTest) ... ok
test_reset_release_with_more_rpm_cruft (unit.common_tests.VersionMathTest) ... ok
test_reset_release_with_rpm_cruft (unit.common_tests.VersionMathTest) ... ok
test_underscore_release (unit.common_tests.VersionMathTest) ... ok
test_unknown_version (unit.common_tests.VersionMathTest) ... ok
test_conformance (unit.pep8_tests.TestPep8) ... ok
test_exceptions_3 (unit.pep8_tests.UglyHackishTest) ... ok
test_import_commands (unit.pep8_tests.UglyHackishTest) ... ok
test_print_function (unit.pep8_tests.UglyHackishTest) ... ok
test_use_commands (unit.pep8_tests.UglyHackishTest) ... ok
test_empty_branch_raises_exception (unit.test_build_target_parser.BuildTargetParserTests) ... ok
test_empty_target_raises_exception (unit.test_build_target_parser.BuildTargetParserTests) ... ok
test_invalid_branch_raises_exception (unit.test_build_target_parser.BuildTargetParserTests) ... ok
test_missing_semicolon_raises_exception (unit.test_build_target_parser.BuildTargetParserTests) ... ok
test_multiple_branches_supported (unit.test_build_target_parser.BuildTargetParserTests) ... ok
test_multiple_spaces_ok (unit.test_build_target_parser.BuildTargetParserTests) ... ok
test_parser_gets_correct_targets (unit.test_build_target_parser.BuildTargetParserTests) ... ok
test_calculate_checksum (unit.test_tar.TarTest) ... ok
test_create_extended_header (unit.test_tar.TarTest) ... ok
test_encode_header (unit.test_tar.TarTest) ... ok
test_fix (unit.test_tar.TarTest) ... ok
test_fix_fails_unless_file_in_binary_mode (unit.test_tar.TarTest) ... ok
test_full_read (unit.test_tar.TarTest) ... ok
test_full_read_buffer_underflow (unit.test_tar.TarTest) ... ok
test_full_read_eventual_buffer_underflow (unit.test_tar.TarTest) ... ok
test_padded_size_length_long (unit.test_tar.TarTest) ... ok
test_padded_size_length_over (unit.test_tar.TarTest) ... ok
test_padded_size_length_small (unit.test_tar.TarTest) ... ok
test_padded_size_length_spot_on (unit.test_tar.TarTest) ... ok

======================================================================
ERROR: test suite for <class 'functional.build_tito_tests.BuildTitoTests'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/nose/suite.py", line 154, in run
    self.setUp()
  File "/usr/lib/python2.6/site-packages/nose/suite.py", line 202, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.6/site-packages/nose/suite.py", line 225, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.6/site-packages/nose/util.py", line 453, in try_run
    return func()
  File "/home/sandbox/test/functional/build_tito_tests.py", line 38, in setUpClass
    self.output_dir
  File "/home/sandbox/test/functional/fixture.py", line 103, in tito
    return CLI().main(argstring.split(' '))
  File "/home/sandbox/src/tito/cli.py", line 202, in main
    return module.main(argv)
  File "/home/sandbox/src/tito/cli.py", line 367, in main
    return builder.run(self.options)
  File "/home/sandbox/src/tito/builder/main.py", line 151, in run
    self.rpm()
  File "/home/sandbox/src/tito/builder/main.py", line 474, in rpm
    BuilderBase.rpm(self)
  File "/home/sandbox/src/tito/builder/main.py", line 261, in rpm
    error_out('%s' % msg)
  File "/home/sandbox/src/tito/common.py", line 236, in error_out
    sys.exit(1)
SystemExit: 1

======================================================================
ERROR: test_simple_build_no_tag (functional.fetch_tests.FetchBuilderTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sandbox/test/functional/fetch_tests.py", line 79, in test_simple_build_no_tag
    (self.output_dir, self.source_filename))
  File "/home/sandbox/test/functional/fixture.py", line 103, in tito
    return CLI().main(argstring.split(' '))
  File "/home/sandbox/src/tito/cli.py", line 202, in main
    return module.main(argv)
  File "/home/sandbox/src/tito/cli.py", line 367, in main
    return builder.run(self.options)
  File "/home/sandbox/src/tito/builder/main.py", line 151, in run
    self.rpm()
  File "/home/sandbox/src/tito/builder/main.py", line 261, in rpm
    error_out('%s' % msg)
  File "/home/sandbox/src/tito/common.py", line 236, in error_out
    sys.exit(1)
SystemExit: 1
-------------------- >> begin captured stdout << ---------------------


Testing in: /tmp/tmpXooSIF-titotest

Creating tito metadata in: /tmp/tmpXooSIF-titotest/.tito
   - created /tmp/tmpXooSIF-titotest/.tito
   - wrote tito.props
   - created /tmp/tmpXooSIF-titotest/.tito/packages
   - wrote /tmp/tmpXooSIF-titotest/.tito/packages/.readme
   - committed to git
Looking for .spec in /tmp/tmpXooSIF-titotest/extsrc
Using file: extsrc.spec
Determined package name to be: extsrc
Loaded package specific tito.props overrides
Unable to locate package specific config for this package.
---- Builder class is None
Importing tito.builder.FetchBuilder
Using builder class: <class 'tito.builder.fetch.FetchBuilder'>
Building in temp dir: /tmp/tmpgBdSm_-titotestoutput/rpmbuild-extsrcdMmtUF
Fetching sources...
Importing tito.builder.fetch.ArgSourceStrategy
Got sources: ['extsrc-0.0.2.tar.gz']
  extsrc.spec
Extracting version/release from: extsrc-0.0.2.tar.gz
Building version: 0.0.2
Building release: 1%{?dist}
rpmbuild --define "_source_filedigest_algorithm md5"  --define "_binary_filedigest_algorithm md5"  --eval '%undefine scl' --define "_topdir /tmp/tmpgBdSm_-titotestoutput/rpmbuild-extsrcdMmtUF" --define "_sourcedir /tmp/tmpgBdSm_-titotestoutput/rpmbuild-extsrcdMmtUF/SOURCES" --define "_builddir /tmp/tmpgBdSm_-titotestoutput/rpmbuild-extsrcdMmtUF/BUILD" --define "_srcrpmdir /tmp/tmpgBdSm_-titotestoutput" --define "_rpmdir /tmp/tmpgBdSm_-titotestoutput"   --noclean -ba /tmp/tmpgBdSm_-titotestoutput/rpmbuild-extsrcdMmtUF/SOURCES/extsrc.spec
--noclean: unknown option




--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_tag_with_custom_message_bad_placeholder (functional.singleproject_tests.SingleProjectTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sandbox/test/functional/singleproject_tests.py", line 121, in test_tag_with_custom_message_bad_placeholder
    self.assertIn("Unknown placeholder 'ultimate_answer' in tag_commit_message_format",
AttributeError: 'SingleProjectTests' object has no attribute 'assertIn'
-------------------- >> begin captured stdout << ---------------------


Testing in: /tmp/tmpkVFeDm-titotest

Creating tito metadata in: /tmp/tmpkVFeDm-titotest/.tito
   - created /tmp/tmpkVFeDm-titotest/.tito
   - wrote tito.props
   - created /tmp/tmpkVFeDm-titotest/.tito/packages
   - wrote /tmp/tmpkVFeDm-titotest/.tito/packages/.readme
   - committed to git
Looking for .spec in /tmp/tmpkVFeDm-titotest
Using file: titotestpkg.spec
Determined package name to be: titotestpkg
Unable to locate package specific config for this package.
Importing tito.tagger.VersionTagger
Using tagger class: <class 'tito.tagger.main.VersionTagger'>
Looking for .spec in /tmp/tmpkVFeDm-titotest
Using file: titotestpkg.spec
Looking for .spec in /tmp/tmpkVFeDm-titotest
Using file: titotestpkg.spec
Getting latest package info from: /tmp/tmpkVFeDm-titotest/.tito/packages/titotestpkg
Getting latest package info from: /tmp/tmpkVFeDm-titotest/.tito/packages/titotestpkg
Cargo.toml file not found, this is probably not a Rust project
No destination version file found, skipping.
Found setup.py, attempting to update version.

   View: git show HEAD
   Undo: tito tag -u
   Push: git push origin && git push origin titotestpkg-0.0.1-1

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_autosetup (unit.common_tests.MungeSetupMacroTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sandbox/test/unit/common_tests.py", line 689, in test_autosetup
    munge_setup_macro(self.SOURCE, line))
  File "/home/sandbox/src/tito/common.py", line 712, in munge_setup_macro
    macro = "{} -p1".format(macro)
ValueError: zero length field name in format

----------------------------------------------------------------------
Ran 129 tests in 33.863s

FAILED (errors=4)
```

</details>

**Comment by dgoodwin** [comment]
Looks like legit test failures to me, the --noclean failure is a recent change, must not be valid for rpmbuild on EL6.

The autosetup feels like it might be a Python 2 vs 3 issue surfacing.

**Comment by stevekuznetsov** [comment]
This is fixed now.
