### ISSUE TITLE
Building srpm is failing

### ISSUE THREAD

**Issue by rmestrum** [dgoodwin/tito#254]
The build of a srpm fails with the following message:

```
tito build --srpm --offline
Building package [testrpm1-2-1]
Wrote: /tmp/tito/testrpm1-2.tar.gz
error: Bad file: /tmp/tito/rpmbuild-testrpm1Ui6UQV/SOURCES/test.txt: No such file or directory



RPM build errors:
    Bad file: /tmp/tito/rpmbuild-testrpm1Ui6UQV/SOURCES/test.txt: No such file or directory


Traceback (most recent call last):
  File "/bin/tito", line 5, in <module>
    pkg_resources.run_script('tito==0.6.9', 'tito')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1462, in run_script
    exec_(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 41, in exec_
    exec("""exec code in globs, locs""")
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/tito-0.6.9-py2.7.egg/EGG-INFO/scripts/tito", line 23, in <module>
    
  File "build/bdist.linux-x86_64/egg/tito/cli.py", line 202, in main
  File "build/bdist.linux-x86_64/egg/tito/cli.py", line 367, in main
  File "build/bdist.linux-x86_64/egg/tito/builder/main.py", line 148, in run
  File "build/bdist.linux-x86_64/egg/tito/builder/main.py", line 223, in srpm
  File "build/bdist.linux-x86_64/egg/tito/common.py", line 447, in run_command_print
tito.exception.RunCommandException: Error running command: rpmbuild --define "_source_filedigest_algorithm md5"  --define "_binary_filedigest_algorithm md5"  --eval '%undefine scl' --define "_topdir /tmp/tito/rpmbuild-testrpm1Ui6UQV" --define "_sourcedir /tmp/tito/rpmbuild-testrpm1Ui6UQV/SOURCES" --define "_builddir /tmp/tito/rpmbuild-testrpm1Ui6UQV/BUILD" --define "_srcrpmdir /tmp/tito" --define "_rpmdir /tmp/tito"   --nodeps -bs /tmp/tito/rpmbuild-testrpm1Ui6UQV/SOURCES/testrpm1-2/testrpm1.spec
```

I'm using tito 0.6.9 on CentOS Linux release 7.3.1611 (Core)

**Comment by xsuchy** [comment]
I suppose that:
`grep Source *spec`
will give you something like:
`Source1: test.txt`
This is wrong when using Tito. Tito will create the sources itself. Tito will git-archive whole directory and pass it as Source0. You should not pass any additional sources.

**Comment by jmrodri** [comment]
What's the spec file look like?

**Comment by rmestrum** [comment]
My specfile looks like this:

```
cat testrpm1.spec 
Name:           testrpm1
Version:        4
Release:        1%{?dist}
Summary:        test
Group:          Development/Tools
License:        Commercial
Source0:        test.txt

BuildArch:      noarch
BuildRoot:      %(mktemp -ud %{_tmppath}/%{name}-%{version}-%{release}-XXXXXX)

%description

%prep


%build
# Er hoeft niets gecompileerd te worden

%install
mkdir -p $RPM_BUILD_ROOT/%{_datadir}/
install -m0644 %{SOURCE0} $RPM_BUILD_ROOT/%{_datadir}/

%files
%{_datadir}/test.txt

%changelog
```

When i run `rpmlint ` on this specfile I get no errors or warnings

**Comment by xsuchy** [comment]
This is good for `rpmbuild` but Tito assume either:
`Source: https://somedomain/some/path/%{name}-%{version}.tar.gz`
or
`Source: %{name}-%{version}.tar.gz`

Tito will create that tar file for you.

**Comment by rmestrum** [comment]
Problem solved. The files that should be included in the RPM where not at the git tag.
