### ISSUE TITLE
Add support for Ubuntu 16.04

### ISSUE THREAD

**Issue by chris1984** [dgoodwin/tito#258]
Not everyone use Fedora, please add support for Ubuntu 16.04

**Comment by stevekuznetsov** [comment]
What issues are you running into, specifically, on Ubuntu? I was trying to set up some of the tests to run on Ubuntu and noticed it was very difficult to get the `rpm` library dependencies. Is there something in `tito` specifically that makes it hard to use on Ubuntu, or is it mostly dependencies?

**Comment by dgoodwin** [comment]
Curious if this was a request to be able to build rpms on Ubuntu with tito, or a much more involved request for dpkg building support.

**Comment by chris1984** [comment]
Hi,

This is the error I am getting:

chrobert@vault111:~/Dropbox/git/tito$ tito init
Traceback (most recent call last):
  File "/usr/local/bin/tito", line 4, in <module>
    __import__('pkg_resources').run_script('tito==0.6.10', 'tito')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/tito-0.6.10-py2.7.egg/EGG-INFO/scripts/tito", line 19, in <module>
    
  File "build/bdist.linux-x86_64/egg/tito/cli.py", line 22, in <module>
  File "build/bdist.linux-x86_64/egg/tito/common.py", line 31, in <module>
ImportError: No module named blessings

Sorry for the delay.

**Comment by chris1984** [comment]
After talking with @dgoodwin going to close this out and I will spin up a Fedora vm somewhere to use.
