### ISSUE TITLE
Error when running 'tito init'

### ISSUE THREAD

**Issue by ashearer23** [dgoodwin/tito#321]
I am running the install on a CentOS 7.4 virtual machine. I copied the codebase over from a git clone of the project. I run the commands to install it from source and when I go to run a 'tito init' I get the following error:

[root@cent74 tito]# tito init
Traceback (most recent call last):
  File "/usr/bin/tito", line 5, in <module>
    pkg_resources.run_script('tito==0.6.11', 'tito')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1462, in run_script
    exec_(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 41, in exec_
    exec("""exec code in globs, locs""")
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/tito-0.6.11-py2.7.egg/EGG-INFO/scripts/tito", line 19, in <module>

  File "build/bdist.linux-x86_64/egg/tito/cli.py", line 23, in <module>
  File "build/bdist.linux-x86_64/egg/tito/common.py", line 31, in <module>
ImportError: No module named blessings

**Comment by dgoodwin** [comment]
If installing from source you are bypassing the rpm requirements which should be covered by the spec file. I would consult tito.spec for the dependencies you need to install if you're going to run from source, in this case python2-blessings or python3-blessings, you're probably going to discover other missing packages as well. 

Tito is available in EPEL for CentOS 7 for what it's worth which should bypass this hassle. 

If you're actually looking to write patches for tito, I suggest installing from EPEL, and then checking out tito.git and replace the installed rpm with your latest committed code, tito build --rpm --test -i.

**Comment by dgoodwin** [comment]
Closing for now as I don't think there's any issue to be fixed here, but we can reopen if necessary.

**Comment by jmrodri** [comment]
@dgoodwin mentioned closing back in May, so I'll do it since it wasn't done.
