### ISSUE TITLE
Tito build of tito fails in master

### ISSUE THREAD

**Issue by jmrodri** [dgoodwin/tito#337]
```
[jesusr@transam tito{master}]$ tito build --test --rpm
Creating output directory: /tmp/candlepin-build
Building package [tito-0.6.11-1]
ERROR: Error running command: cd /tmp/candlepin-build/rpmbuild-titokmp2qa9v/SOURCES/ && tar xzf tito-git-19.03509b3.tar.gz

Status code: 2

Command output: tar: Skipping to next header
tar: Exiting with failure status due to previous errors

Traceback (most recent call last):
  File "/usr/bin/tito", line 23, in <module>
    CLI().main(sys.argv[1:])
  File "/usr/lib/python3.7/site-packages/tito/cli.py", line 203, in main
    return module.main(argv)
  File "/usr/lib/python3.7/site-packages/tito/cli.py", line 378, in main
    return builder.run(self.options)
  File "/usr/lib/python3.7/site-packages/tito/builder/main.py", line 156, in run
    self.rpm()
  File "/usr/lib/python3.7/site-packages/tito/builder/main.py", line 514, in rpm
    self.tgz()
  File "/usr/lib/python3.7/site-packages/tito/builder/main.py", line 497, in tgz
    self._setup_sources()
  File "/usr/lib/python3.7/site-packages/tito/builder/main.py", line 537, in _setup_sources
    self.tgz_filename))
  File "/usr/lib/python3.7/site-packages/tito/common.py", line 426, in run_command
    raise RunCommandException(command, status, output)
tito.exception.RunCommandException: Error running command: cd /tmp/candlepin-build/rpmbuild-titokmp2qa9v/SOURCES/ && tar xzf tito-git-19.03509b3.tar.gz
```

**Comment by jmrodri** [comment]
Reverting to commit 77d54e657963cbcd7389df2f14a8ece9b954edaa resolves the problem. Seems that this commit has introduced the issue: https://github.com/dgoodwin/tito/commit/03509b36d5cf151955ed8739266b4799782147ac


```
[jesusr@transam tito{master}]$ git reset --hard 77d54e657963cbcd7389df2f14a8ece9b954edaa
HEAD is now at 77d54e6 Add missing dependency declarations.

[jesusr@transam tito{master}]$ tito build --test --rpm                                                                                                                                  
Creating output directory: /tmp/candlepin-build                                                                                                                                         
Building package [tito-0.6.11-1]                                                                                                                                                             
Wrote: /tmp/candlepin-build/tito-git-18.77d54e6.tar.gz                                                                                                                  
                                                                                                                                                                                             
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.dpcugu                                                                                                                                         
+ umask 022                                                                                                                                                                                  
+ cd /tmp/candlepin-build/rpmbuild-titoomfqv5sr/BUILD                                                                                                                                        
+ cd /tmp/candlepin-build/rpmbuild-titoomfqv5sr/BUILD                                                                                                                                        
+ rm -rf tito-git-18.77d54e6                                                                                                                                                       
+ /usr/bin/gzip -dc /tmp/candlepin-build/rpmbuild-titoomfqv5sr/SOURCES/tito-git-18.77d54e6.tar.gz                                                                                            
+ /usr/bin/tar -xof -                                                                                                                                                                        
+ STATUS=0                                                                                                                                                                                    
+ '[' 0 -ne 0 ']'                                                                                                                                                                            
+ cd tito-git-18.77d54e6                                                                                                                                                                     
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .                                                                                                                                                      
+ sed -i '1s|#!.*|#!/usr/bin/python3|' bin/tito                                                                                                                                               + exit 0                                                                                                                                                                                      Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.F1czxb                                                                                                                                   
+ umask 022                                                                                                                                                                                   
+ cd /tmp/candlepin-build/rpmbuild-titoomfqv5sr/BUILD                                                                                                                                   
+ cd tito-git-18.77d54e6                                                                                                                                                              
+ /usr/bin/python3 setup.py build                                                                                                                                                             
running build                                        
running build_py                                                                              
....
+ exit 0


Successfully built: /tmp/candlepin-build/tito-0.6.11-1.git.18.77d54e6.fc29.src.rpm
        - /tmp/candlepin-build/noarch/tito-0.6.11-1.git.18.77d54e6.fc29.noarch.rpm
```

**Comment by xsuchy** [comment]
This is cause by presence of
```
test/unit/resources/archivé.tar
test/unit/resources/les_misérables.tar
```
if you try to unpack tarball created by tito, it will contain errors. Plain `git archive` creates the correct tarball. I suspect that there is an error in that tarball mangling which tries to preserve the same checksum.
