### ISSUE TITLE
tito build --test --rpm -i tracebacks on Fedora 31

### ISSUE THREAD

**Issue by xsuchy** [dgoodwin/tito#341]
On Fedora 31 I got this:
```
~/projects/mock/mock{devel}]130$ tito build --test --rpm -i
....
+ exit 0


Successfully built: /tmp/tito/mock-1.4.19-1.git.8.0c138c8.fc31.src.rpm
        - /tmp/tito/noarch/mock-scm-1.4.19-1.git.8.0c138c8.fc31.noarch.rpm
        - /tmp/tito/noarch/mock-lvm-1.4.19-1.git.8.0c138c8.fc31.noarch.rpm
        - /tmp/tito/noarch/mock-1.4.19-1.git.8.0c138c8.fc31.noarch.rpm
Auto-installing packages:
Traceback (most recent call last):
  File "/usr/bin/tito", line 23, in <module>
    CLI().main(sys.argv[1:])
  File "/usr/lib/python3.7/site-packages/tito/cli.py", line 203, in main
    return module.main(argv)
  File "/usr/lib/python3.7/site-packages/tito/cli.py", line 378, in main
    return builder.run(self.options)
  File "/usr/lib/python3.7/site-packages/tito/builder/main.py", line 157, in run
    self._auto_install()
  File "/usr/lib/python3.7/site-packages/tito/builder/main.py", line 330, in _auto_install
    reinstall = self.package_manager.is_installed(self.project_name, self.build_version)
  File "/usr/lib/python3.7/site-packages/tito/builder/main.py", line 1309, in is_installed
    iv = "%s-%s" % (q.version.decode("utf-8"), q.release.decode("utf-8"))
AttributeError: 'str' object has no attribute 'decode'

$ rpm -q tito
tito-0.6.11-9.fc31.noarch
```

**Comment by xsuchy** [comment]
It is caused by
  https://rpm.org/wiki/Releases/4.15.0
Fix Python 3 to return string data as surrogate-escaped utf-8 strings instead of bytes which nothing else in the API accepts
